---
- name: Install memcached
  apt:
    pkg:
      - memcached
    state: present
    update_cache: yes

- name: Deploy memcached config
  template:
    src: memcached.conf.j2
    dest: /etc/memcached.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart memcached

- name: Enable and start memcached
  systemd:
    name: memcached
    enabled: yes
    state: started
