---
memcached_memory: 512
memcached_tcp_port: 11211
memcached_udp_port: 0
memcached_listen: 0.0.0.0
memcached_maxconn: 1024
memcached_max_object_size: 1m
memcached_logfile: /var/log/memcached.log
memcached_user: memcache
memcached_group: memcache
