---
- name: Install MySQL Server & Client packages
  apt:
    pkg:
      - mysql-server
      - mysql-client
    state: present
    update_cache: yes
  when: mysql_environment != 'production'
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: mysql_server_installed
  notify: start mysql

- name: Install MySQL Client Package
  apt:
    pkg:
      - mysql-client
    state: present
    update_cache: yes
  when: mysql_environment == 'production'
  environment:
    DEBIAN_FRONTEND: noninteractive
  register: mysql_client_installed

- name: MySQL configurations for XL AWS Instance
  blockinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    block: |
      max_allowed_packet=67108864
      key_buffer_size=64M
      max_allowed_packet=64M
      join_buffer_size=512K
      max_connections=3000
      innodb_buffer_pool_size=12G
      innodb_log_file_size=1G
      innodb_buffer_pool_instances=12
  when: mysql_environment != 'production'

- name: Install Alternative for /etc/alternatives/my.cnf
  command: 'update-alternatives --install /etc/mysql/my.cnf my.cnf /etc/mysql/mysql.cnf 200'
  when: mysql_environment != 'production'
  become: yes
  become_user: root
  notify: restart mysql
