---
- name: Install MySQL packages
  apt:
    pkg:
      - mysql-server
      - mysql-client
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: start mysql
  service:
    name: mysql
    state: started
