---
- name: Add PPA
  shell: "add-apt-repository -y ppa:ondrej/php"
  become: yes
  become_user: root

- name: Apt Update
  apt:
    update_cache: yes

- name: Install PHP and Dependencies
  apt:
    pkg:
      - php8.3-fpm
      - php8.3-cli
      - php8.3-mysql
      - php8.3-intl
      - php8.3-ldap
      - php8.3-sqlite3
      - php8.3-curl
      - php8.3-xsl
      - php8.3-imap
      - php8.3-imagick
      - php8.3-memcached
      - php8.3-zip
      - php8.3-mbstring
      - php-json
      - php8.3-soap
      - php8.3-xml
      - php8.3-gd
    state: present

- name: Install Composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755
    validate_certs: no

- name: Configure php8.3-fpm pool.
  lineinfile:
    dest: "/etc/php/8.3/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - regexp: "^listen.?=.+$"
      line: "listen = /run/php/php8.3-fpm.sock"
    - regexp: "^pm.max_children.?=.+$"
      line: "pm.max_children = 120"
    - regexp: "^pm.start_servers.?=.+$"
      line: "pm.start_servers = 10"
    - regexp: "^pm.min_spare_servers.?=.+$"
      line: "pm.min_spare_servers = 10"
    - regexp: "^pm.max_spare_servers.?=.+$"
      line: "pm.max_spare_servers = 20"
    - regexp: "^;pm.max_requests.?=.+$"
      line: "pm.max_requests = 500"

- name: Configure php8.3 php.ini
  lineinfile:
    dest: "/etc/php/8.3/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - regexp: "^post_max_size.?=.+$"
      line: "post_max_size = 108M"
    - regexp: "^upload_max_filesize.?=.+$"
      line: "upload_max_filesize = 100M"
    - regexp: "^session.gc_probability.?=.+$"
      line: "session.gc_probability = 1"
    - regexp: "^zend.assertions.?=.+$"
      line: "zend.assertions = 1"
  notify: restart php8.3-fpm
