---
- name: Add PPA
  shell: "add-apt-repository -y ppa:ondrej/php"
  become: true
  become_user: root

- name: Apt Update
  apt:
    update_cache: yes

- name: Install PHP and Dependencies
  apt:
    pkg:
      - php8.4-fpm
      - php8.4-cli
      - php8.4-mysql
      - php8.4-intl
      - php8.4-ldap
      - php8.4-sqlite3
      - php8.4-curl
      - php8.4-xsl
      - php8.4-imap
      - php8.4-imagick
      - php8.4-memcached
      - php8.4-zip
      - php8.4-mbstring
      - php-json
      - php8.4-soap
      - php8.4-xml
      - php8.4-gd
    state: present

- name: Install Composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755

- name: Configure php8.4-fpm pool.
  lineinfile:
    dest: "/etc/php/8.4/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - regexp: "^listen.?=.+$"
      line: "listen = /run/php/php8.4-fpm.sock"
    - regexp: "^pm.max_children.?=.+$"
      line: "pm.max_children = 120"
    - regexp: "^pm.start_servers.?=.+$"
      line: "pm.start_servers = 10"
    - regexp: "^pm.min_spare_servers.?=.+$"
      line: "pm.min_spare_servers = 10"
    - regexp: "^pm.max_spare_servers.?=.+$"
      line: "pm.max_spare_servers = 20"
    - regexp: "^;pm.max_requests.?=.+$"
      line: "pm.max_requests = 500"

- name: Configure php8.4 php.ini
  lineinfile:
    dest: "/etc/php/8.4/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  with_items:
    - regexp: "^post_max_size.?=.+$"
      line: "post_max_size = 108M"
    - regexp: "^upload_max_filesize.?=.+$"
      line: "upload_max_filesize = 100M"
    - regexp: "^session.gc_probability.?=.+$"
      line: "session.gc_probability = 1"
    - regexp: "^zend.assertions.?=.+$"
      line: "zend.assertions = 1"
  notify: restart php8.4-fpm
