---
- name: Install PHP and extensions
  apt:
    pkg: "{{ php_packages }}"
    state: present
    update_cache: yes

- name: Install Composer
  get_url:
    url: https://getcomposer.org/download/latest-stable/composer.phar
    dest: /usr/local/bin/composer
    mode: '0755'

- name: Configure php{{ php_version }}-fpm pool
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  loop:
    - regexp: "^listen.?=.+$"
      line: "listen = /run/php/php{{ php_version }}-fpm.sock"
    - regexp: "^pm.max_children.?=.+$"
      line: "pm.max_children = {{ php_fpm_max_children }}"
    - regexp: "^pm.start_servers.?=.+$"
      line: "pm.start_servers = {{ php_fpm_start_servers }}"
    - regexp: "^pm.min_spare_servers.?=.+$"
      line: "pm.min_spare_servers = {{ php_fpm_min_spare_servers }}"
    - regexp: "^pm.max_spare_servers.?=.+$"
      line: "pm.max_spare_servers = {{ php_fpm_max_spare_servers }}"
    - regexp: "^;?pm.max_requests.?=.+$"
      line: "pm.max_requests = {{ php_fpm_max_requests }}"
  notify: restart php-fpm

- name: Configure php{{ php_version }} php.ini
  lineinfile:
    dest: "/etc/php/{{ php_version }}/fpm/php.ini"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
    backrefs: yes
  loop:
    - regexp: "^post_max_size.?=.+$"
      line: "post_max_size = {{ php_post_max_size }}"
    - regexp: "^upload_max_filesize.?=.+$"
      line: "upload_max_filesize = {{ php_upload_max_filesize }}"
    - regexp: "^memory_limit.?=.+$"
      line: "memory_limit = {{ php_memory_limit }}"
    - regexp: "^max_execution_time.?=.+$"
      line: "max_execution_time = {{ php_max_execution_time }}"
    - regexp: "^session.gc_probability.?=.+$"
      line: "session.gc_probability = 0"
    - regexp: "^zend.assertions.?=.+$"
      line: "zend.assertions = 1"
  notify: restart php-fpm

- name: Enable and start php{{ php_version }}-fpm
  systemd:
    name: "php{{ php_version }}-fpm"
    enabled: yes
    state: started
