---
- name: Install MySQL server
  apt:
    pkg:
      - mysql-server
    state: present
    update_cache: yes
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Enable and start MySQL
  systemd:
    name: mysql
    enabled: yes
    state: started
