---
- name: Build the Development Environment
  hosts: development
  module_defaults:
    apt:
      force_apt_get: yes
  user: ubuntu
  become: true
  become_user: root
  vars:
    app_path: "/var/www/cakephp-app"
    app_name: "cakephp-app"
    become_alternate_user: "ubuntu"
  roles:
    - {role: "system", tags: "system"}
    - {role: "libssl", tags: "libssl"}
    - {role: "chrony", tags: "chrony"}
    - {role: "php", tags: "php"}
    - {role: "nginx", tags: "nginx"}
    - {role: "wkhtmltopdf", tags: "wkhtmltopdf"}
    - {role: "mysql", tags: "mysql"}
    - {role: "memcached", tags: "memcached"}
    - {role: "nodejs", tags: "nodejs"}
    - {role: "crontab", tags: "crontab"}
    - {role: "mailpit", tags: "mailpit"}
  tasks:
    - name: make a symbolic link for application crontab file
      file:
        src: "{{ app_path }}/cron.d/development"
        dest: "/etc/cron.d/{{ app_name }}"
        state: link

    - name: install composer dependencies
      composer:
        command: install
        no_dev: no
        working_dir: "{{ app_path }}"
      become: true
      become_user: "{{ become_alternate_user }}"
      ignore_errors: true

    - name: Install gulp globally
      shell: "source ~/.nvm/nvm.sh && npm install -g gulpjs/gulp-cli"
      become: true
      become_user: "{{ become_alternate_user }}"
      args:
        executable: /bin/bash

    - name: Install node packages for application
      shell: "source ~/.nvm/nvm.sh && cd {{ app_path }} && npm install"
      become: true
      become_user: "{{ become_alternate_user }}"
      args:
        executable: /bin/bash

    - name: Create CakePHP dev config from default
      copy:
        src: "{{ app_path }}/config/app_local.example.php"
        dest: "{{ app_path }}/config/app_local.php"
        remote_src: yes
        force: no

    - name: Create /var/files/
      file:
        path: "/var/files/"
        state: directory
        owner: www-data
        group: www-data
        mode: 0755

    - name: restart nginx
      service:
        name: nginx
        state: restarted

    - name: restart php8.4-fpm
      service:
        name: php8.4-fpm
        state: restarted

    - name: Create MySQL ubuntu user
      shell: "mysql -e \"CREATE USER IF NOT EXISTS 'ubuntu'@'%' IDENTIFIED WITH mysql_native_password BY 'ubuntu'\";"
      become: true
      become_user: root

    - name: Grant the MySQL ubuntu user some permissions
      shell: "mysql -e \"GRANT ALL on *.* to 'ubuntu'@'%' WITH GRANT OPTION\";"
      become: true
      become_user: root

    - name: Flushing the MySQL Privileges
      shell: "mysql -e \"FLUSH PRIVILEGES\";"
      become: true
      become_user: root

    - name: Create the MySQL Database for the project
      shell: "mysql -e \"CREATE DATABASE IF NOT EXISTS cakephp_app DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_general_ci;\";"
      become: true
      become_user: root

    - name: Check if app migrations have already been ran
      shell: "mysql -e \"SELECT * FROM information_schema.tables WHERE table_schema = 'cakephp_app'\";"
      become: true
      become_user: root
      register: migrationran # above query returns nothing when no tables exist

    - name: Run app migrations
      command: "{{ app_path }}/bin/cake migrations migrate -vvvv"
      when: migrationran.stdout == "" # stdout of the variable we just registered will be empty when no tables exist
      ignore_errors: true
