---
- name: Install WkHtmlToPdf Dependencies
  apt:
    pkg:
      - libxrender1
      - libfontconfig1
      - libx11-dev
      - libjpeg62
      - libxtst6
      - fontconfig
      - xfonts-75dpi
      - xfonts-base
    state: present

- name: Set WkHtmlToPdf download URL based on architecture
  set_fact:
    wkhtmltopdf_download_url: >-
      {% if ansible_facts["architecture"] == 'aarch64' %}
        https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_arm64.deb
      {% else %}
        https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
      {% endif %}

- name: 'Download WkHtmlToPdf'
  get_url:
    url: "{{ wkhtmltopdf_download_url }}"
    dest: /root/wkhtmltopdf.deb
    force: false
    validate_certs: no

- name: 'Install WkHtmlToPdf'
  command: dpkg -i /root/wkhtmltopdf.deb
