---
- name: start and enable mailhog
  service:
    name: mailhog
    state: started
    enabled: yes

- name: restart mailhog
  service:
    name: mailhog
    state: restarted

- name: start mailhog
  service:
    name: mailhog
    state: started