---
- name: Install nginx
  apt:
    pkg:
      - nginx
    state: present
    update_cache: yes

- name: Deploy nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Deploy site configs
  template:
    src: "sites-available/{{ item.config }}.j2"
    dest: "/etc/nginx/sites-available/{{ item.server_name }}.conf"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ nginx_configurations }}"
  notify: restart nginx

- name: Enable site configs
  file:
    src: "/etc/nginx/sites-available/{{ item.server_name }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ item.server_name }}.conf"
    state: link
  loop: "{{ nginx_configurations }}"
  notify: restart nginx

- name: Remove default site symlink
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Enable and start nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
