---
- name: Set libssl1.1 download URL based on architecture
  set_fact:
    libssl_download_url: >-
      {% if ansible_facts["architecture"] == 'aarch64' %}
        http://ports.ubuntu.com/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_arm64.deb
      {% else %}
        http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      {% endif %}

- name: 'Download libssl1.1'
  get_url:
    url: "{{ libssl_download_url }}"
    dest: /root/libssl.deb
    force: false
    validate_certs: no

- name: 'Install libssl1.1'
  command: dpkg -i /root/libssl.deb
