---
- name: Build crontab from fragments
  template:
    src: concat.j2
    dest: "{{ playbook_dir }}/../roles/crontab/templates/{{ item }}.txt"
  loop: "{{ active_crontab_files | list }}"
  delegate_to: localhost
  become: false

- name: Deploy crontab files
  template:
    src: "{{ item }}.txt"
    dest: "{{ app_path }}/cron.d/{{ item }}"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ active_crontab_files | list }}"
